// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByqYMbw5F-1swYhwRYUJwgJPw7tRocBrE',
    appId: '1:289568467867:web:d352f7198202a5792e0f3e',
    messagingSenderId: '289568467867',
    projectId: 'meyaa-gp-57e82',
    authDomain: 'meyaa-gp-57e82.firebaseapp.com',
    storageBucket: 'meyaa-gp-57e82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ZC2mAbaq_Z89UMiAuP1C-0BnAwpunE8',
    appId: '1:289568467867:android:943027bb3f77221e2e0f3e',
    messagingSenderId: '289568467867',
    projectId: 'meyaa-gp-57e82',
    storageBucket: 'meyaa-gp-57e82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk5Ovc_2tTEdkewBmdfSUqO3IiASs9Piw',
    appId: '1:289568467867:ios:cb915102a52d971d2e0f3e',
    messagingSenderId: '289568467867',
    projectId: 'meyaa-gp-57e82',
    storageBucket: 'meyaa-gp-57e82.appspot.com',
    androidClientId: '289568467867-e7sb0cjv1ef2hq7kk3fl1mpdl7ld34ur.apps.googleusercontent.com',
    iosClientId: '289568467867-rmror5s139vvfpul16o7k56ubhgra3e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.MEYAA-GP1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk5Ovc_2tTEdkewBmdfSUqO3IiASs9Piw',
    appId: '1:289568467867:ios:cb915102a52d971d2e0f3e',
    messagingSenderId: '289568467867',
    projectId: 'meyaa-gp-57e82',
    storageBucket: 'meyaa-gp-57e82.appspot.com',
    androidClientId: '289568467867-e7sb0cjv1ef2hq7kk3fl1mpdl7ld34ur.apps.googleusercontent.com',
    iosClientId: '289568467867-rmror5s139vvfpul16o7k56ubhgra3e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.MEYAA-GP1',
  );
}
